name: Build and Push Extension ZIP to gh-pages

on:
  push:
    branches:
      - feature-project-setup

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Build the code bundle
        run: |
          npm i
          npm run build
    
      - name: Zip the src directory
        run: |
          mkdir -p chatgptbookmark
          mkdir -p dist
          cp -r public/* chatgptbookmark/
          zip -r dist/chatgptbookmark.zip public

      - name: Deploy ZIP to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages